image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  type: build
  script:
  - npm install gulp-cli -g
  - npm install
  - gulp styles
  - gulp scripts
  - gulp images
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 week


development:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_DEVELOPMENT_APP --api-key=$HEROKU_DEVELOPMENT_API_KEY
  only:
  - master

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY
  only:
  - staging

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - production
